{% set name = "zocalo" %}
{% set version = "0.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 725a0f92d1647d7055a9396c99a7036099a90ff287cba71f3d2fddfed4c0aac7

build:
  number: 0
  noarch: python
  entry_points:
    - zocalo.service = zocalo.service:start_service
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - graypy
    - python
    - setuptools
    - stomp.py
    - workflows

test:
  imports:
    - zocalo
    - zocalo.service
  commands:
    - zocalo.service --help

about:
  home: https://github.com/DiamondLightSource/zocalo-python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Infrastructure components for automated data processing at Diamond Light Source
  doc_url: https://zocalo.readthedocs.io/en/latest/
  dev_url: https://github.com/DiamondLightSource/zocalo-python

extra:
  recipe-maintainers:
    - anthchirp
