{% set name = "zocalo" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zocalo-{{ version }}.tar.gz
  sha256: 58aca6e214899afd59c2be73a617d31993275d111074728cd54adf457a4e85c6

build:
  number: 0
  noarch: python
  entry_points:
    - zocalo.dlq_check = zocalo.cli.dlq_check:run
    - zocalo.dlq_purge = zocalo.cli.dlq_purge:run
    - zocalo.dlq_reinject = zocalo.cli.dlq_reinject:run
    - zocalo.go = zocalo.cli.go:run
    - zocalo.queue_drain = zocalo.cli.queue_drain:run
    - zocalo.service = zocalo.service:start_service
    - zocalo.shutdown = zocalo.cli.shutdown:run
    - zocalo.wrap = zocalo.cli.wrap:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - graypy >=1.0
    - marshmallow
    - pydantic
    - python >=3.8
    - pyyaml
    - requests
    - setuptools
    - workflows >=2.14

test:
  imports:
    - zocalo
    - zocalo.cli
    - zocalo.configuration
    - zocalo.service
  commands:
    - pip check
    - zocalo.service --help
  requires:
    - pip

about:
  home: https://pypi.org/project/zocalo/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Infrastructure components for automated data processing at Diamond Light Source
  doc_url: https://zocalo.readthedocs.io/en/latest/
  dev_url: https://github.com/DiamondLightSource/zocalo-python

extra:
  recipe-maintainers:
    - anthchirp
    - ndevenish
    - rjgildea
