{% set name = "zocalo" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zocalo-{{ version }}.tar.gz
  sha256: cdb29073d495c26049c69a4aec57a14972c768866e426de8004b02560e556c15

build:
  number: 0
  noarch: python
  entry_points:
    - zocalo.dlq_check = zocalo.cli.dlq_check:run
    - zocalo.dlq_purge = zocalo.cli.dlq_purge:run
    - zocalo.dlq_reinject = zocalo.cli.dlq_reinject:run
    - zocalo.go = zocalo.cli.go:run
    - zocalo.queue_drain = zocalo.cli.queue_drain:run
    - zocalo.service = zocalo.service:start_service
    - zocalo.shutdown = zocalo.cli.shutdown:run
    - zocalo.wrap = zocalo.cli.wrap:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - poetry-core >1.5,<2
  run:
    - graypy ~=2.0
    - marshmallow >3.19,<4
    - pydantic >2,<3
    - python >=3.10
    - pyyaml >6,<7
    - requests >2.31,<3
    - workflows >=2.26,<3

test:
  imports:
    - zocalo
    - zocalo.cli
    - zocalo.configuration
    - zocalo.service
  commands:
    - pip check
    - zocalo.service --help
  requires:
    - pip

about:
  home: https://pypi.org/project/zocalo/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Infrastructure components for automated data processing at Diamond Light Source
  doc_url: https://zocalo.readthedocs.io/en/latest/
  dev_url: https://github.com/DiamondLightSource/zocalo-python

extra:
  recipe-maintainers:
    - anthchirp
    - ndevenish
    - rjgildea
