{% set name = "zocalo" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zocalo-{{ version }}.tar.gz
  sha256: a715be40342d0ced0b6155f78bcac416c01ac59f4d990b263f84d5b97652aee2

build:
  number: 0
  noarch: python
  entry_points:
    - zocalo.go = zocalo.cli.go:run
    - zocalo.service = zocalo.service:start_service
    - zocalo.wrap = zocalo.cli.wrap:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - graypy >=1.0
    - marshmallow
    - python >=3.6
    - pyyaml
    - setuptools
    - workflows >=2.7

test:
  imports:
    - zocalo
    - zocalo.cli
    - zocalo.configuration
    - zocalo.service
  commands:
    - pip check
    - zocalo.service --help
  requires:
    - pip

about:
  home: https://pypi.org/project/zocalo/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Infrastructure components for automated data processing at Diamond Light Source
  doc_url: https://zocalo.readthedocs.io/en/latest/
  dev_url: https://github.com/DiamondLightSource/zocalo-python

extra:
  recipe-maintainers:
    - anthchirp
